version: '3.1'
services:
  paris-admin:
    image: 192.168.1.126/library/fjs/paris-admin-uat:master
    deploy:
      replicas: 2
      update_config: 
        parallelism: 1   #每次更新复本数量
        delay: 2s        #每次更新间隔
      resources:
        limits:
          cpus: "0.5"
          memory: 2100M
      restart_policy:
        condition: on-failure
    networks:
      fjs_overlay_master:
        aliases:
          - paris-admin
    ports:
      - "1321:80"
networks:
  fjs_overlay_master:
    external:
      name: fjs_overlay_master
